

### [C] tag 생성
POST http://10.201.235.221:8082/projects/1/tags
X-USER-ID: 1
Content-Type: application/json

{
  "name": "태그"
}

### [R] tag
GET http://10.201.235.221:8082/tags/1
X-USER-ID: 1


### [D] tag 삭제
DELETE http://10.201.235.221:8082/tags/7
X-USER-ID: 1


### [U] tag 업데이트
PUT http://10.201.235.221:8082/tags/7
X-USER-ID: 1
Content-Type: application/json

{
    "name": "수정"
}